[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'frankier/neovim-colors-solarized-truecolor-only'

# コメントON/OFFを手軽に実行
[[plugins]]
repo = 'tomtom/tcomment_vim'

# シングルクオートとダブルクオートの入れ替え等
[[plugins]]
repo = 'tpope/vim-surround'

# インデントに色を付けて見やすくする
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
         \'colorscheme': 'solarized',
         \'active': {
          \  'left': [
          \    ['mode', 'paste'],
          \    ['readonly', 'filename', 'modified'],
          \    ['ale'],
          \    [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ]
          \  ]
          \}
    \}
'''

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add = '''
let g:lightline.component_expand = {
      \  'linter_checking': 'lightline#ale#checking',
      \  'linter_warnings': 'lightline#ale#warnings',
      \  'linter_errors': 'lightline#ale#errors',
      \  'linter_ok': 'lightline#ale#ok',
      \ }
let g:lightline.component_type = {
      \     'linter_checking': 'left',
      \     'linter_warnings': 'warning',
      \     'linter_errors': 'error',
      \     'linter_ok': 'left',
      \ }
'''

# 非同期構文チェック
[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'plasticboy/vim-markdown'
